CREATE TABLE model_test_records (
  id CHAR(36) NOT NULL,
  admin_user_id CHAR(36) NULL,
  provider_id CHAR(36) NOT NULL,
  provider_model_id CHAR(36) NOT NULL,
  provider_credential_id CHAR(36) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'CREATING',
  request_json JSON NOT NULL,
  create_url VARCHAR(1000) NOT NULL,
  create_http_status SMALLINT UNSIGNED NULL,
  create_duration_ms INT UNSIGNED NULL,
  create_response_json JSON NULL,
  remote_task_id VARCHAR(191) NULL,
  query_url VARCHAR(1000) NULL,
  query_http_status SMALLINT UNSIGNED NULL,
  query_duration_ms INT UNSIGNED NULL,
  query_response_json JSON NULL,
  error_message VARCHAR(2000) NULL,
  last_queried_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_model_test_records_created (created_at),
  KEY idx_model_test_records_model_created (provider_model_id, created_at),
  KEY idx_model_test_records_status_created (status, created_at),
  CONSTRAINT fk_model_test_records_admin FOREIGN KEY (admin_user_id) REFERENCES admin_users(id),
  CONSTRAINT fk_model_test_records_provider FOREIGN KEY (provider_id) REFERENCES providers(id),
  CONSTRAINT fk_model_test_records_model FOREIGN KEY (provider_model_id) REFERENCES provider_models(id),
  CONSTRAINT fk_model_test_records_credential FOREIGN KEY (provider_credential_id) REFERENCES provider_credentials(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
