"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { apiRequest } from "@/lib/api";

type Category={id:string;code:string;name:string;description:string;sort_order:number;status:string;script_count:number};
type ScriptRow={id:string;category_id:string;category_name:string;title:string;duration_seconds:number;summary:string;content:string;canonical_json:unknown;heat_score:number;use_count:number;sort_order:number;status:string};
type Config={credit_cost:number;revision:number};
const emptyCanonical={schema_version:"aivs-script-v1",story:{title:"",logline:"",genre:[],theme:"",synopsis:"",tone:"",aspect_ratio:"9:16",visual_style:"",beats:[]},episodes:[],characters:[],scenes:[],props:[],sequences:[],shots:[]};
const errorText=(value:unknown)=>value instanceof Error?value.message:"操作失败";

export function ScriptLibraryPanel({token}:{token:string}){
  const [categories,setCategories]=useState<Category[]>([]);const [scripts,setScripts]=useState<ScriptRow[]>([]);const [config,setConfig]=useState<Config>();const [cost,setCost]=useState(20);const [editingCategory,setEditingCategory]=useState<Category|"new">();const [editingScript,setEditingScript]=useState<ScriptRow|"new">();const [error,setError]=useState("");const [message,setMessage]=useState("");
  const load=useCallback(async()=>{try{const [nextCategories,nextScripts,nextConfig]=await Promise.all([apiRequest<Category[]>("/admin/script-library/categories",{},token),apiRequest<ScriptRow[]>("/admin/script-library/scripts",{},token),apiRequest<Config>("/admin/script-library/config",{},token)]);setCategories(nextCategories);setScripts(nextScripts);setConfig(nextConfig);setCost(nextConfig.credit_cost);setError("");}catch(reason){setError(errorText(reason));}},[token]);
  useEffect(()=>{void load();},[load]);
  const saveCost=async(event:FormEvent)=>{event.preventDefault();if(!config)return;try{const next=await apiRequest<Config>("/admin/script-library/config",{method:"PATCH",body:JSON.stringify({credit_cost:cost,revision:config.revision})},token);setConfig(next);setCost(next.credit_cost);setMessage("剧本库积分价格已保存");setError("");}catch(reason){setError(errorText(reason));}};
  const removeCategory=async(row:Category)=>{if(!window.confirm(`确定删除分类“${row.name}”吗？`))return;try{await apiRequest(`/admin/script-library/categories/${row.id}`,{method:"DELETE"},token);await load();}catch(reason){setError(errorText(reason));}};
  const removeScript=async(row:ScriptRow)=>{if(!window.confirm(`确定删除剧本“${row.title}”吗？历史积分流水仍会保留。`))return;try{await apiRequest(`/admin/script-library/scripts/${row.id}`,{method:"DELETE"},token);await load();}catch(reason){setError(errorText(reason));}};
  return <div className="script-library-admin">
    <section className="section-card"><header><div><span className="kicker">LIBRARY PRICING</span><h2>剧本库定价</h2><p>用户每次从剧本库一键生成项目时扣除的固定积分。</p></div></header><form onSubmit={saveCost}><label>每个剧本生成项目所需积分<input type="number" min="0" max="1000000" step="0.000001" value={cost} onChange={event=>setCost(Number(event.target.value))}/></label><footer><button className="primary">保存定价</button></footer></form></section>
    <section className="section-card table-card"><header><div><span className="kicker">SCRIPT CATEGORIES</span><h2>剧本分类</h2><p>分类停用后，其下剧本不会在客户端展示。</p></div><button className="primary" onClick={()=>setEditingCategory("new")}>新增分类</button></header><div className="table-scroll"><table><thead><tr><th>分类</th><th>编码</th><th>剧本数</th><th>状态</th><th>排序</th><th>操作</th></tr></thead><tbody>{categories.map(row=><tr key={row.id}><td><strong>{row.name}</strong><small className="cell-note">{row.description}</small></td><td>{row.code}</td><td>{row.script_count}</td><td><span className={`status ${row.status==="ACTIVE"?"good":"bad"}`}>{row.status}</span></td><td>{row.sort_order}</td><td><div className="table-actions"><button className="secondary" onClick={()=>setEditingCategory(row)}>编辑</button><button className="danger-button" onClick={()=>void removeCategory(row)}>删除</button></div></td></tr>)}</tbody></table></div></section>
    <section className="section-card table-card"><header><div><span className="kicker">SCRIPT CATALOG</span><h2>剧本数据</h2><p>内容用于用户预览，规范 JSON 用于直接生成项目；热度首次创建时自动随机生成，使用后继续增长。</p></div><button className="primary" disabled={!categories.length} onClick={()=>setEditingScript("new")}>新增剧本</button></header><div className="table-scroll"><table><thead><tr><th>剧本</th><th>分类</th><th>时长</th><th>热度 / 使用</th><th>状态</th><th>操作</th></tr></thead><tbody>{scripts.map(row=><tr key={row.id}><td><strong>{row.title}</strong><small className="cell-note">{row.summary}</small></td><td>{row.category_name}</td><td>{row.duration_seconds} 秒</td><td>{Number(row.heat_score).toLocaleString()} / {row.use_count}</td><td><span className={`status ${row.status==="ACTIVE"?"good":"bad"}`}>{row.status}</span></td><td><div className="table-actions"><button className="secondary" onClick={()=>setEditingScript(row)}>编辑</button><button className="danger-button" onClick={()=>void removeScript(row)}>删除</button></div></td></tr>)}</tbody></table></div></section>
    {error&&<div className="form-error">{error}</div>}{message&&<div className="form-success">{message}</div>}
    {editingCategory&&<CategoryModal token={token} item={editingCategory==="new"?undefined:editingCategory} onClose={()=>setEditingCategory(undefined)} onSaved={async()=>{setEditingCategory(undefined);await load();}}/>}
    {editingScript&&<ScriptModal token={token} categories={categories} item={editingScript==="new"?undefined:editingScript} onClose={()=>setEditingScript(undefined)} onSaved={async()=>{setEditingScript(undefined);await load();}}/>}
  </div>;
}

function CategoryModal({token,item,onClose,onSaved}:{token:string;item?:Category;onClose:()=>void;onSaved:()=>Promise<void>}){
  const [form,setForm]=useState({code:item?.code||"",name:item?.name||"",description:item?.description||"",sort_order:item?.sort_order??10,status:item?.status||"ACTIVE"});const [error,setError]=useState("");
  const submit=async(event:FormEvent)=>{event.preventDefault();try{await apiRequest(item?`/admin/script-library/categories/${item.id}`:"/admin/script-library/categories",{method:item?"PATCH":"POST",body:JSON.stringify(form)},token);await onSaved();}catch(reason){setError(errorText(reason));}};
  return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><header><div><span className="kicker">SCRIPT CATEGORY</span><h2>{item?"编辑分类":"新增分类"}</h2></div><button type="button" onClick={onClose}>×</button></header><div className="two-columns"><label>分类名称<input value={form.name} onChange={event=>setForm({...form,name:event.target.value})} required/></label><label>分类编码<input value={form.code} onChange={event=>setForm({...form,code:event.target.value.toLowerCase()})} placeholder="short-drama" required/></label></div><label>分类说明<input value={form.description} onChange={event=>setForm({...form,description:event.target.value})}/></label><div className="two-columns"><label>排序<input type="number" min="0" value={form.sort_order} onChange={event=>setForm({...form,sort_order:Number(event.target.value)})}/></label><label>状态<select value={form.status} onChange={event=>setForm({...form,status:event.target.value})}><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></select></label></div>{error&&<div className="form-error">{error}</div>}<footer><button type="button" className="secondary" onClick={onClose}>取消</button><button className="primary">保存</button></footer></form></div>;
}

function ScriptModal({token,categories,item,onClose,onSaved}:{token:string;categories:Category[];item?:ScriptRow;onClose:()=>void;onSaved:()=>Promise<void>}){
  const canonical=typeof item?.canonical_json==="string"?item.canonical_json:JSON.stringify(item?.canonical_json||emptyCanonical,null,2);const [form,setForm]=useState({category_id:item?.category_id||categories[0]?.id||"",title:item?.title||"",duration_seconds:item?.duration_seconds??60,summary:item?.summary||"",content:item?.content||"",canonical,sort_order:item?.sort_order??10,status:item?.status||"ACTIVE"});const [error,setError]=useState("");
  const submit=async(event:FormEvent)=>{event.preventDefault();try{const body={...form,canonical:JSON.parse(form.canonical)};await apiRequest(item?`/admin/script-library/scripts/${item.id}`:"/admin/script-library/scripts",{method:item?"PATCH":"POST",body:JSON.stringify(body)},token);await onSaved();}catch(reason){setError(errorText(reason));}};
  return <div className="modal-backdrop"><form className="modal script-library-editor-modal" onSubmit={submit}><header><div><span className="kicker">LIBRARY SCRIPT</span><h2>{item?"编辑剧本":"新增剧本"}</h2></div><button type="button" onClick={onClose}>×</button></header><div className="two-columns"><label>标题<input value={form.title} onChange={event=>setForm({...form,title:event.target.value})} required/></label><label>分类<select value={form.category_id} onChange={event=>setForm({...form,category_id:event.target.value})}>{categories.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label></div><div className="three-columns"><label>时长（秒）<input type="number" min="0" max="86400" value={form.duration_seconds} onChange={event=>setForm({...form,duration_seconds:Number(event.target.value)})}/></label><label>排序<input type="number" min="0" value={form.sort_order} onChange={event=>setForm({...form,sort_order:Number(event.target.value)})}/></label><label>状态<select value={form.status} onChange={event=>setForm({...form,status:event.target.value})}><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></select></label></div><label>简要描述<textarea className="compact-textarea" value={form.summary} onChange={event=>setForm({...form,summary:event.target.value})} required/></label><label>内容预览<textarea rows={8} value={form.content} onChange={event=>setForm({...form,content:event.target.value})} required/></label><label>规范项目 JSON<textarea rows={18} spellCheck={false} value={form.canonical} onChange={event=>setForm({...form,canonical:event.target.value})} required/><small>必须包含 story、characters、scenes、sequences、shots；建议同时包含 schema_version、episodes、props。</small></label>{error&&<div className="form-error">{error}</div>}<footer><button type="button" className="secondary" onClick={onClose}>取消</button><button className="primary">保存剧本</button></footer></form></div>;
}
