import { BadRequestException, ConflictException, Inject, Injectable, NotFoundException } from "@nestjs/common";
import { randomInt, randomUUID } from "node:crypto";
import { RowDataPacket } from "mysql2/promise";
import { AuditService } from "../common/audit.service";
import { DatabaseService } from "../database/database.service";

type CategoryInput = { code: string; name: string; description?: string; sortOrder: number; status: string };
type ScriptInput = { categoryId: string; title: string; durationSeconds: number; summary?: string; content: string; canonical: unknown; sortOrder: number; status: string };
interface ConfigRow extends RowDataPacket { credit_cost: number | string; revision: number; updated_at: string }
interface ScriptRow extends RowDataPacket { id: string; title: string; duration_seconds: number | string; canonical_json: string | Record<string, unknown>; status: string }

function normalizeStatus(value: string): string { const result=value.toUpperCase(); if (!new Set(["ACTIVE","DISABLED"]).has(result)) throw new BadRequestException("状态不正确"); return result; }
function normalizeSort(value: number): number { if (!Number.isInteger(value)||value<0||value>100000) throw new BadRequestException("排序值必须是 0 到 100000 的整数"); return value; }
function normalizeCredits(value: number): number { if (!Number.isFinite(value)||value<0||value>1_000_000) throw new BadRequestException("积分价格必须是 0 到 1000000 的数字"); return value; }
function normalizeCanonical(value: unknown): Record<string, unknown> {
  let parsed=value; if (typeof parsed==="string") { try { parsed=JSON.parse(parsed); } catch { throw new BadRequestException("规范剧本 JSON 格式错误"); } }
  if (!parsed||typeof parsed!=="object"||Array.isArray(parsed)) throw new BadRequestException("规范剧本必须是 JSON 对象");
  const result=parsed as Record<string,unknown>;
  if (!result.story||!Array.isArray(result.characters)||!Array.isArray(result.scenes)||!Array.isArray(result.sequences)||!Array.isArray(result.shots)) throw new BadRequestException("规范剧本必须包含 story、characters、scenes、sequences、shots");
  if (!Array.isArray(result.episodes)) result.episodes=[]; if (!Array.isArray(result.props)) result.props=[]; return result;
}
function recordNumber(): string { return `SL${Date.now()}${randomUUID().replaceAll("-","").slice(0,10)}`; }

@Injectable()
export class ScriptLibraryService {
  constructor(
    @Inject(DatabaseService) private readonly database: DatabaseService,
    @Inject(AuditService) private readonly audit: AuditService,
  ) {}
  async config() { const rows=await this.database.query<ConfigRow[]>("SELECT credit_cost,revision,updated_at FROM script_library_config WHERE id=1"); const row=rows[0]; if(!row) throw new NotFoundException("剧本库积分配置不存在"); return {...row,credit_cost:Number(row.credit_cost)}; }
  async updateConfig(adminUserId:string,value:number,revision:number) { const cost=normalizeCredits(value); const result=await this.database.execute("UPDATE script_library_config SET credit_cost=?,revision=revision+1,updated_by=? WHERE id=1 AND revision=?",[cost,adminUserId,revision]); if(!result.affectedRows) throw new ConflictException("配置已被其他管理员修改，请刷新后重试"); await this.audit.record({adminUserId,action:"script_library.config.update",entityType:"script_library_config",entityId:"1",details:{creditCost:cost}}); return this.config(); }
  async quote() { const config=await this.config(); return {credits:config.credit_cost,billing_unit:"PER_SCRIPT",config_revision:config.revision}; }
  publicCategories() { return this.database.query<RowDataPacket[]>(`SELECT c.id,c.code,c.name,c.description,c.sort_order,COUNT(s.id) script_count FROM script_library_categories c LEFT JOIN script_library_scripts s ON s.category_id=c.id AND s.status='ACTIVE' WHERE c.status='ACTIVE' GROUP BY c.id ORDER BY CASE WHEN c.code='hot-fans' THEN 0 ELSE 1 END,c.sort_order,c.name`); }
  async publicScripts(query?:string,category?:string) { const values:unknown[]=[]; const where=["s.status='ACTIVE'","c.status='ACTIVE'"]; if(category?.trim()){where.push("c.id=?");values.push(category.trim());} if(query?.trim()){where.push("(s.title LIKE ? OR s.summary LIKE ? OR s.content LIKE ?)");const pattern=`%${query.trim().slice(0,100)}%`;values.push(pattern,pattern,pattern);} return this.database.query<RowDataPacket[]>(`SELECT s.id,s.category_id,c.code category_code,c.name category_name,s.title,s.duration_seconds,s.summary,s.heat_score,s.use_count,s.sort_order,s.updated_at FROM script_library_scripts s INNER JOIN script_library_categories c ON c.id=s.category_id WHERE ${where.join(" AND ")} ORDER BY CASE WHEN c.code='hot-fans' THEN 0 ELSE 1 END,s.sort_order,s.heat_score DESC,s.updated_at DESC LIMIT 200`,values); }
  async publicScript(id:string) { const rows=await this.database.query<RowDataPacket[]>(`SELECT s.id,s.category_id,c.code category_code,c.name category_name,s.title,s.duration_seconds,s.summary,s.content,s.heat_score,s.use_count,s.updated_at FROM script_library_scripts s INNER JOIN script_library_categories c ON c.id=s.category_id WHERE s.id=? AND s.status='ACTIVE' AND c.status='ACTIVE' LIMIT 1`,[id]); if(!rows.length) throw new NotFoundException("剧本不存在或已下架"); return rows[0]; }
  adminCategories() { return this.database.query<RowDataPacket[]>(`SELECT c.*,COUNT(s.id) script_count FROM script_library_categories c LEFT JOIN script_library_scripts s ON s.category_id=c.id GROUP BY c.id ORDER BY c.sort_order,c.name`); }
  adminScripts() { return this.database.query<RowDataPacket[]>(`SELECT s.id,s.category_id,c.name category_name,s.title,s.duration_seconds,s.summary,s.content,s.canonical_json,s.heat_score,s.use_count,s.sort_order,s.status,s.created_at,s.updated_at FROM script_library_scripts s INNER JOIN script_library_categories c ON c.id=s.category_id ORDER BY c.sort_order,s.sort_order,s.updated_at DESC`); }
  private validCategory(input:CategoryInput):CategoryInput { if(!/^[a-z0-9][a-z0-9-]{0,63}$/.test(input.code)) throw new BadRequestException("分类编码只能使用小写字母、数字和短横线"); return {...input,code:input.code.trim(),name:input.name.trim(),description:input.description?.trim()||"",sortOrder:normalizeSort(input.sortOrder),status:normalizeStatus(input.status)}; }
  async createCategory(adminUserId:string,raw:CategoryInput) { const input=this.validCategory(raw),id=randomUUID(); try{await this.database.execute("INSERT INTO script_library_categories(id,code,name,description,sort_order,status) VALUES(?,?,?,?,?,?)",[id,input.code,input.name,input.description,input.sortOrder,input.status]);}catch(error){if((error as {code?:string}).code==="ER_DUP_ENTRY")throw new ConflictException("分类编码已存在");throw error;} await this.audit.record({adminUserId,action:"script_library_category.create",entityType:"script_library_category",entityId:id});return{id}; }
  async updateCategory(adminUserId:string,id:string,raw:CategoryInput) { const input=this.validCategory(raw); try{const result=await this.database.execute("UPDATE script_library_categories SET code=?,name=?,description=?,sort_order=?,status=? WHERE id=?",[input.code,input.name,input.description,input.sortOrder,input.status,id]);if(!result.affectedRows)throw new NotFoundException("分类不存在");}catch(error){if((error as {code?:string}).code==="ER_DUP_ENTRY")throw new ConflictException("分类编码已存在");throw error;} await this.audit.record({adminUserId,action:"script_library_category.update",entityType:"script_library_category",entityId:id});return{updated:true}; }
  async deleteCategory(adminUserId:string,id:string) { const children=await this.database.query<RowDataPacket[]>("SELECT id FROM script_library_scripts WHERE category_id=? LIMIT 1",[id]);if(children.length)throw new ConflictException("请先删除或移动分类下的剧本");const result=await this.database.execute("DELETE FROM script_library_categories WHERE id=?",[id]);if(!result.affectedRows)throw new NotFoundException("分类不存在");await this.audit.record({adminUserId,action:"script_library_category.delete",entityType:"script_library_category",entityId:id});return{deleted:true}; }
  private validScript(input:ScriptInput) { const duration=Number(input.durationSeconds);if(!Number.isInteger(duration)||duration<0||duration>86400)throw new BadRequestException("剧本时长必须是 0 到 86400 秒的整数");return{...input,title:input.title.trim(),summary:input.summary?.trim()||"",content:input.content.trim(),durationSeconds:duration,canonical:normalizeCanonical(input.canonical),sortOrder:normalizeSort(input.sortOrder),status:normalizeStatus(input.status)}; }
  async createScript(adminUserId:string,raw:ScriptInput) { const input=this.validScript(raw),id=randomUUID();const categories=await this.database.query<RowDataPacket[]>("SELECT id FROM script_library_categories WHERE id=?",[input.categoryId]);if(!categories.length)throw new BadRequestException("所选分类不存在");await this.database.execute("INSERT INTO script_library_scripts(id,category_id,title,duration_seconds,summary,content,canonical_json,heat_score,sort_order,status) VALUES(?,?,?,?,?,?,?,?,?,?)",[id,input.categoryId,input.title,input.durationSeconds,input.summary,input.content,JSON.stringify(input.canonical),randomInt(500,100001),input.sortOrder,input.status]);await this.audit.record({adminUserId,action:"script_library_script.create",entityType:"script_library_script",entityId:id});return{id}; }
  async updateScript(adminUserId:string,id:string,raw:ScriptInput) { const input=this.validScript(raw);const result=await this.database.execute("UPDATE script_library_scripts SET category_id=?,title=?,duration_seconds=?,summary=?,content=?,canonical_json=?,sort_order=?,status=? WHERE id=?",[input.categoryId,input.title,input.durationSeconds,input.summary,input.content,JSON.stringify(input.canonical),input.sortOrder,input.status,id]);if(!result.affectedRows)throw new NotFoundException("剧本不存在");await this.audit.record({adminUserId,action:"script_library_script.update",entityType:"script_library_script",entityId:id});return{updated:true}; }
  async deleteScript(adminUserId:string,id:string) { const result=await this.database.execute("DELETE FROM script_library_scripts WHERE id=?",[id]);if(!result.affectedRows)throw new NotFoundException("剧本不存在");await this.audit.record({adminUserId,action:"script_library_script.delete",entityType:"script_library_script",entityId:id});return{deleted:true}; }
  async useScript(userId:string,scriptId:string,idempotencyKey:string,expectedCredits:number) {
    const prior=await this.database.query<RowDataPacket[]>("SELECT id,script_id_snapshot,title_snapshot,duration_seconds_snapshot,canonical_snapshot,credits_consumed FROM script_library_usages WHERE user_id=? AND idempotency_key=? LIMIT 1",[userId,idempotencyKey]);
    if(prior[0]){const replay=prior[0];if(replay.script_id_snapshot!==scriptId)throw new ConflictException("相同幂等键对应了不同剧本");return{usage_id:replay.id,script_id:replay.script_id_snapshot,title:replay.title_snapshot,duration_seconds:Number(replay.duration_seconds_snapshot||0),canonical:typeof replay.canonical_snapshot==="string"?JSON.parse(replay.canonical_snapshot):replay.canonical_snapshot,credits:Number(replay.credits_consumed),idempotent_replay:true};}
    const config=await this.config(),cost=normalizeCredits(config.credit_cost);if(!Number.isFinite(expectedCredits)||expectedCredits!==cost)throw new ConflictException("剧本库积分价格已变化，请重新确认");
    return this.database.transaction(async connection=>{
      const [replays]=await connection.query<RowDataPacket[]>("SELECT id,script_id_snapshot,title_snapshot,duration_seconds_snapshot,canonical_snapshot,credits_consumed FROM script_library_usages WHERE user_id=? AND idempotency_key=? LIMIT 1",[userId,idempotencyKey]);const replay=replays[0];if(replay){if(replay.script_id_snapshot!==scriptId)throw new ConflictException("相同幂等键对应了不同剧本");return{usage_id:replay.id,script_id:replay.script_id_snapshot,title:replay.title_snapshot,duration_seconds:Number(replay.duration_seconds_snapshot||0),canonical:typeof replay.canonical_snapshot==="string"?JSON.parse(replay.canonical_snapshot):replay.canonical_snapshot,credits:Number(replay.credits_consumed),idempotent_replay:true};}
      const [scripts]=await connection.query<ScriptRow[]>("SELECT s.id,s.title,s.duration_seconds,s.canonical_json,s.status FROM script_library_scripts s INNER JOIN script_library_categories c ON c.id=s.category_id WHERE s.id=? AND s.status='ACTIVE' AND c.status='ACTIVE' LIMIT 1 FOR UPDATE",[scriptId]);const script=scripts[0];if(!script)throw new NotFoundException("剧本不存在或已下架");
      const [accounts]=await connection.query<RowDataPacket[]>("SELECT id FROM ledger_accounts WHERE owner_type='USER' AND owner_id=? AND account_type='AVAILABLE' AND currency='CREDIT' LIMIT 1 FOR UPDATE",[userId]);if(!accounts.length)throw new NotFoundException("用户积分账户不存在");const [balances]=await connection.query<RowDataPacket[]>("SELECT COALESCE(SUM(amount),0) balance FROM ledger_entries WHERE account_id=?",[accounts[0]!.id]);const [holds]=await connection.query<RowDataPacket[]>("SELECT COALESCE(SUM(amount),0) held FROM credit_holds WHERE user_id=? AND status='ACTIVE'",[userId]);if(Number(balances[0]?.balance||0)-Number(holds[0]?.held||0)<cost)throw new ConflictException("可用积分不足");
      const [pricingRows]=await connection.query<RowDataPacket[]>("SELECT cny_per_credit FROM model_credit_pricing_config WHERE id=1");
      const cnyPerCredit=Number(pricingRows[0]?.cny_per_credit);if(!Number.isFinite(cnyPerCredit)||cnyPerCredit<=0)throw new ConflictException("积分人民币比例配置无效");
      const usageId=randomUUID(),transactionId=randomUUID(),consumptionId=randomUUID(),canonicalValue=typeof script.canonical_json==="string"?JSON.parse(script.canonical_json):script.canonical_json;
      await connection.execute("INSERT INTO ledger_transactions(id,transaction_type,reference_type,reference_id,metadata_json) VALUES(?,'SCRIPT_LIBRARY_CONSUMPTION','script_library_usage',?,?)",[transactionId,usageId,JSON.stringify({script_id:scriptId,title:script.title})]);
      await connection.execute("INSERT INTO ledger_entries(id,transaction_id,account_id,amount) VALUES(?,?,?,?)",[randomUUID(),transactionId,accounts[0]!.id,-cost]);
      await connection.execute("INSERT INTO credit_consumption_records(id,consumption_no,user_id,category,credits_consumed,revenue_cny_per_credit,cost_credits,status,description,metadata_json,occurred_at) VALUES(?,?,?,'SCRIPT_LIBRARY',?,?,0,'CONFIRMED',?,?,UTC_TIMESTAMP(3))",[consumptionId,recordNumber(),userId,cost,cnyPerCredit,`剧本库《${script.title}》生成项目`,JSON.stringify({script_id:scriptId,usage_id:usageId})]);
      await connection.execute("INSERT INTO script_library_usages(id,user_id,script_id,script_id_snapshot,idempotency_key,title_snapshot,duration_seconds_snapshot,canonical_snapshot,credits_consumed,consumption_record_id) VALUES(?,?,?,?,?,?,?,?,?,?)",[usageId,userId,scriptId,scriptId,idempotencyKey,script.title,Number(script.duration_seconds||0),JSON.stringify(canonicalValue),cost,consumptionId]);
      await connection.execute("UPDATE script_library_scripts SET use_count=use_count+1,heat_score=heat_score+? WHERE id=?",[randomInt(1,11),scriptId]);return{usage_id:usageId,script_id:scriptId,title:script.title,duration_seconds:Number(script.duration_seconds||0),canonical:canonicalValue,credits:cost};
    });
  }
}
