const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const baseUrl = process.env.TEST_BASE_URL || 'http://127.0.0.1:1420';
  const appSource = fs.readFileSync(path.join(__dirname, '../src/App.tsx'), 'utf8');
  assert.match(appSource, /!showShotDetail && <DirectorWorkbench[\s\S]*?一键生成所有分镜视频[\s\S]*?一键合成视频/);
  assert.match(appSource, /onGenerateImage=\{\(shotId\) => generateImage\.mutate\(shotId\)\}/);
  assert.match(appSource, /onGenerateVideo=\{\(shotId\) => void startShotVideoGeneration\(shotId\)\}/);
  assert.match(appSource, /onEditVideoPrompt=\{\(shotId\) => \{ setSelectedShotId\(shotId\); setVideoPromptEditorShotId\(shotId\); \}\}/);
  assert.match(appSource, /showShotDetail && <section className="project-video-composer">/);
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(`${baseUrl}/test/director-workbench.html`);
    await page.getByRole('heading', { name: '导演工作台' }).waitFor();
    await page.getByRole('button', { name: '一键生成所有分镜视频' }).waitFor();
    await page.getByRole('button', { name: '一键合成视频' }).waitFor();
    assert.equal(await page.locator('.director-heading .director-stats').count(), 1);
    assert.equal(await page.locator('.director-heading .director-actions').count(), 1);
    const modeControl = page.getByRole('group', { name: '显示模式' });
    assert.equal(await modeControl.getByRole('button', { name: '列表', exact: true }).getAttribute('aria-pressed'), 'true');
    assert.equal(await modeControl.getByRole('button', { name: '大图', exact: true }).getAttribute('aria-pressed'), 'false');
    const headingOrder = await page.locator('.director-heading-tools').evaluate(element => Array.from(element.children).map(child => child.className));
    assert.deepEqual(headingOrder, ['director-stats', 'director-view-mode', 'director-actions']);
    assert.equal(await page.locator('.director-list-card').count(), 8);
    const cardTops = await page.locator('.director-list-card').evaluateAll(elements => elements.map(element => element.getBoundingClientRect().y));
    assert.ok(cardTops.slice(0, 5).every(top => Math.abs(top - cardTops[0]) < 1), 'first row should contain five cards');
    assert.ok(cardTops[5] > cardTops[0], 'sixth card should start a new row');
    assert.equal(await page.locator('.director-list-card').first().locator('.director-list-tags span').count(), 4);
    const cardActions = page.locator('.director-list-card').first().locator('.director-list-actions button');
    assert.equal(await cardActions.count(), 3);
    assert.deepEqual(await cardActions.allTextContents(), ['生成分镜图', '生成视频', '编辑提示词']);
    assert.equal(await cardActions.locator('svg').count(), 0);
    const topControlHeights = await page.locator('.director-stats > span, .director-view-mode, .director-actions > button').evaluateAll(elements => elements.map(element => element.getBoundingClientRect().height));
    assert.ok(Math.max(...topControlHeights) - Math.min(...topControlHeights) < 1, 'top cards, mode control, and action buttons should share one height');
    assert.equal(topControlHeights[0], 54);
    const promptPreview = page.locator('.director-list-card').first().locator('.director-list-prompt');
    assert.equal(await promptPreview.locator('p').evaluate(element => getComputedStyle(element).webkitLineClamp), '2');
    await promptPreview.hover();
    assert.equal(await promptPreview.getByRole('tooltip').isVisible(), true);
    await page.locator('.director-list-card').nth(1).click();
    assert.match(await page.getByRole('status').textContent(), /详情:SHOT_002/);
    await page.locator('.director-list-card').first().getByRole('button', { name: '编辑提示词' }).click();
    assert.match(await page.getByRole('status').textContent(), /编辑:SHOT_001/);
    await modeControl.getByRole('button', { name: '大图', exact: true }).click();
    assert.equal(await modeControl.getByRole('button', { name: '大图', exact: true }).getAttribute('aria-pressed'), 'true');
    assert.equal(await page.locator('.director-card').count(), 8);
    assert.equal(await page.locator('.director-detail-left .director-detail-block').count(), 2);
    assert.equal(await page.locator('.director-detail-center .director-detail-block').count(), 2);
    assert.equal(await page.locator('.director-detail-right .director-parameter').count(), 6);
    assert.equal(await page.locator('.director-strip-heading').count(), 0);
    assert.equal(await page.getByText('画风设定', { exact: true }).count(), 0);
    const prompt = page.locator('.director-detail-block.prompt');
    assert.equal(await prompt.locator('button').count(), 0);
    assert.equal(await prompt.locator('p').evaluate(element => getComputedStyle(element).overflowY), 'auto');
    assert.equal(await prompt.locator('p').evaluate(element => element.scrollHeight > element.clientHeight), true);
    const detail = await page.locator('.director-selected').boundingBox();
    const strip = await page.locator('.director-strip').boundingBox();
    assert.ok(strip.y > detail.y + detail.height, 'horizontal cards should sit below selected-shot details');
    assert.equal(await page.locator('.director-strip').evaluate(element => element.scrollWidth > element.clientWidth), true);
    const columns = await page.locator('.director-detail-grid > *').evaluateAll(elements => elements.map(element => element.getBoundingClientRect().width));
    assert.ok(columns[1] > columns[0] * 1.8 && columns[1] < columns[0] * 2.2, 'center column should be one half and side columns one quarter');
    const columnBottoms = await page.locator('.director-detail-grid > *').evaluateAll(elements => elements.map(element => { const box = element.getBoundingClientRect(); return box.y + box.height; }));
    assert.ok(Math.max(...columnBottoms) - Math.min(...columnBottoms) < 1, 'detail columns should share one bottom edge');
    assert.ok((await page.locator('.director-detail-block.media.large > div').boundingBox()).height < 280, 'storyboard video area should be compact');
    await page.getByLabel('按制作状态筛选').selectOption('running');
    assert.equal(await page.locator('.director-card').count(), 1);
    await page.getByLabel('按制作状态筛选').selectOption('');
    await page.getByRole('textbox', { name: '搜索分镜' }).fill('SHOT_003');
    assert.equal(await page.locator('.director-card').count(), 1);
    await page.locator('.director-card').click();
    assert.match(await page.getByRole('status').textContent(), /SHOT_003/);
    assert.match(await page.locator('.director-selected > header h3').textContent(), /SHOT_003/);
    await page.getByRole('textbox', { name: '搜索分镜' }).fill('');
    if (process.env.UI_SCREENSHOT) await page.screenshot({ path: process.env.UI_SCREENSHOT, fullPage: true });
    for (const width of [1000, 700, 540, 375]) {
      await page.setViewportSize({ width, height: 900 });
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, `overflow at ${width}px`);
    }
    await page.setViewportSize({ width: 700, height: 900 });
    await page.evaluate(() => { document.documentElement.style.fontSize = '20px'; });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'overflow with enlarged text');
    await page.evaluate(() => { document.documentElement.style.fontSize = ''; });
    await page.setViewportSize({ width: 1440, height: 900 });
    await page.goto(`${baseUrl}/test/director-workbench.html?script`);
    const picker = await page.locator('.file-picker').boundingBox();
    const downloadButton = await page.getByRole('button', { name: '下载规范剧本示例' }).boundingBox();
    assert.ok(downloadButton.x >= picker.x + picker.width);
    assert.equal(downloadButton.y, picker.y);
    const notice = await page.locator('.script-analysis-notice').boundingBox();
    const createButton = await page.getByRole('button', { name: '创建本地项目（分析剧本需积分）' }).boundingBox();
    assert.ok(Math.abs(notice.x + notice.width - createButton.x - createButton.width) < 1);
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: '下载规范剧本示例' }).click();
    const download = await downloadPromise;
    assert.match(download.suggestedFilename(), /\.txt$/);
    const txt = require('node:fs').readFileSync(await download.path(), 'utf8');
    assert.match(txt, /一、项目剧情/);
    assert.match(txt, /四、分镜列表/);
    assert.match(txt, /第2段（7～19秒）/);
    if (process.env.UI_SCREENSHOT) await page.screenshot({ path: process.env.UI_SCREENSHOT.replace('.png', '-script.png'), fullPage: true });
    assert.deepEqual(errors, []);
    console.log('PASS: director three-column detail, top actions, horizontal cards, filtering, responsive layout, script buttons alignment and TXT download');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
